In [1]:
import numpy as np
import inspect
from typing import Union

from numpy.lib.function_base import average

In [2]:
rng = np.random.RandomState()

In [3]:
a = rng.uniform(0.,1.,20)
print(a)

[0.30381246 0.70630297 0.81677879 0.35471426 0.50280948 0.34702062
 0.02575593 0.83941705 0.76293252 0.89890003 0.011494   0.01344426
 0.23253903 0.85335763 0.58145809 0.6700216  0.38317504 0.13748106
 0.62424021 0.8439637 ]


In [5]:
ay =a.min()
print(ay)

0.011494003839905065


In [6]:
b = a - np.max([ay, 0.3]) <= 0.001
print(b)

[False False False False False False  True False False False  True  True
  True False False False False  True False False]


In [7]:
p = rng.randint(0, 20, (5, 3))
print(p)

[[18 16  6]
 [16  5  9]
 [12 18 11]
 [ 3  0 18]
 [ 1 16  5]]


In [3]:
c = np.random.choice(20, 5, replace=False)
print(c)

[10 11 16 17  3]


In [7]:
print(p[2])

[ 7 15 13]


In [4]:
print(arr.shape)

(10, 100, 3)


In [4]:
a = [0.07558338, 0.08669577, 0.04180792, 0.08776797, 0.03730544, 0.0864414, 0.06398179, 0.05931514, 0.08570248, 0.08633546, 0.06880476, 0.08442494, 0.05248505, 0.08334856]
t = 0
for i in a:
    t += i
print(t)


1.00000006
